name: Laravel

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
         XDEBUG_MODE: coverage
         DB_CONNECTION: sqlite
         DB_DATABASE: database/database.sqlite
        run: php -dpcov.enabled=1 vendor/bin/phpunit --testdox -d memory_limit=512M --coverage-clover clover.xml

      - name: Execute analysis (PHPStan) via Larastan
        run: vendor/bin/phpstan analyse

      - name: Upload coverage to Codecov.io
        shell: bash
        run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f ${GITHUB_WORKSPACE}/clover.xml -C ${GITHUB_SHA}
        env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
